version: '3.8'

services:
  front-end:
    container_name: heyvoca_front_stg
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: staging
    ports:
      - "3001:80"
    env_file:
      - .env.stg
    networks:
      - heyvoca_front_stg_network
    restart: unless-stopped

networks:
  heyvoca_front_stg_network:
    driver: bridge
