version: '3.8'

services:
  front-end:
    container_name: heyvoca_front_local
    image: whrksp126/heyvoca_front:local
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    networks:
      - heyvoca_front_local_network
    restart: unless-stopped

networks:
  heyvoca_front_local_network:
    driver: bridge