version: '3.8'

services:
  front-end:
    container_name: heyvoca_front_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3002:3000"
    env_file:
      - .env.dev
    environment:
      - VITE_ALLOWED_HOSTS=dev.heyvoca_front.ghmate.com
    networks:
      - heyvoca_front_dev_network
    restart: unless-stopped

networks:
  heyvoca_front_dev_network:
    driver: bridge
